vich_uploader:
    db_driver: orm

    mappings:
        photo_file:
            uri_prefix: /realisations
            upload_destination: '%upload_directory%'
        logo_file:
            uri_prefix: /skills
            upload_destination: '%upload_directory%/skills'